import { Box } from '@chakra-ui/react'
import Head from 'next/head'

export default function Shop() {
  return (
    <div>
      <Head>
        <title>Shop</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Box>My Shop</Box>
    </div>
  )
}
