import { Box, Flex, Grid, Heading, Image, Text } from '@chakra-ui/react'
import Head from 'next/head'
import Link from 'next/link'
import Product from '../../components/product'

export default function Products({ products }) {
  return (
    <div>
      <Head>
        <title>NextJS E-Shop - Products</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Box p="0 8%" mt={15} mb={15}>
        <Heading>All my products</Heading>
        <Flex
          direction="column"
          justifyContent="center"
          maxW={{ xl: '1200px' }}
          m="0 auto"
          minH="100vh"
        >
          <Grid
            w="full"
            gridGap="5"
            gridTemplateColumns="repeat( auto-fit, minmax(300px, 1fr) )"
          >
            {products.products.map((product) => (
              <Box key={product.id}>
                <Link href={`/products/${product.id}`}>
                  <a>
                    <Product
                      imageSrc={product.image[0]}
                      imageAlt={product.name}
                      title={product.name}
                      category={product.category}
                      price={product.price}
                    />
                  </a>
                </Link>
              </Box>
            ))}
          </Grid>
        </Flex>
      </Box>
    </div>
  )
}

export async function getServerSideProps() {
  const products = await fetch('https://kds-js.github.io/shop.json').then((r) =>
    r.json()
  )
  return {
    props: {
      products,
    },
  }
}
