import { Box } from '@chakra-ui/react'
import Head from 'next/head'
import Footer from '../components/footer'
import Header from '../components/header'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box>My home page</Box>
    </div>
  )
}
